name: Frontend Tests
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
      working-directory: ./frontend
    - name: Run tests
      run: yarn test
      working-directory: ./frontend